### ISSUE TITLE
Consolidate CRD and examples for OPA discovery / configuration

### ISSUE THREAD

**Issue by maltesander** [stackabletech/kafka-operator#363]
Currently we define OPA in Kafka like this:
```
apiVersion: kafka.stackable.tech/v1alpha1
kind: KafkaCluster
metadata:
  name: simple-kafka
spec:
  version: 3.1.0
  zookeeperConfigMapName: simple-kafka-znode
  opa:
    configMapName: opa-simple
    authorizerClassName: org.openpolicyagent.kafka.OpaAuthorizer
    authorizerCacheInitialCapacity: 0
    authorizerCacheMaximumSize: 0
    authorizerCacheExpireAfterSeconds: 0
[...]
```

We want to consolidate the custom resource example to look like the other operators:
```
apiVersion: kafka.stackable.tech/v1alpha1
kind: KafkaCluster
metadata:
  name: simple-kafka
spec:
  version: 3.1.0
  zookeeperConfigMapName: simple-kafka-znode
  opaConfigMapName: opa-simple
  config:
    configOverrides:
      server.properties: 
        opa.authorizer.cache.expire.after.seconds: "0"
[...]
```
This means the following tasks must be completed:
- [x] Remove OPA struct and replace with `opaConfigMapName` for the discovery config map
- [x] Remove the `authorizerClassName` (see https://github.com/stackabletech/kafka-operator/issues/350)
- [x] Make the config parameters (e.g. `authorizerCacheExpireAfterSeconds`) configurable (or only overrideable) 
- [x] Decide on sensible defaults (which can be configured/overriden), see https://github.com/anderseknert/opa-kafka-plugin/blob/main/README.md 

This will be a breaking change.
