### ISSUE TITLE
Setting advertised listeners is not propagated to broker

### ISSUE THREAD

**Issue by berndfo** [stackabletech/kafka-operator#564]
### Affected version

 docker.stackable.tech/stackable/kafka-operator:23.1.0

### Current and expected behavior

Requirement: Giving access to Kafka brokers from within a k8s cluster. 

Currently, only the external cluster IP is per default advertised by brokers. For my particular setup, this IP:port address isn't and shouldn't be accessible, not from inside or outside of the cluster.

When trying to set the `advertised.listeners` property of Kafka through `KafkaCluster`, it is not picked up by the broker configuration, see configuration below. This results in Kafka being effectively not usable in this particular scenario.

```yaml
  brokers:
    roleGroups:
      default1:
        replicas: 1    
      rg1:
        replicas: 1
        configOverrides:
          server.properties:
            advertised.listeners: CLIENT://stack-kafka-broker-rg1-0.mynamespace:9092
```
kcat shows that brokers still advertise the original external ip regardless of the override.

### Would you like to work on fixing this bug?

None
