### ISSUE TITLE
Re-Installing Kafka fails - Cluster id doesn't match

### ISSUE THREAD

**Issue by paulocabrita-ionos** [stackabletech/kafka-operator#609]
### Affected version

23.4.1

### Current and expected behavior

Current: the reinstallation of the Kafka fails with the error "The Cluster ID 4a...... doesn't match stored clusterid Some(Qgt.....) in meta.properties.
Expected: reinstallation of a Kafka cluster without issue.

Steps done:
- created an IONOS K8S cluster;
- installed stackable's operators (version 23.4.1);
- created 2 yaml files (zookeeper and kafka);
- applied both of them and everything worked perfectly;
- deleted zookeeper and kafka using the yaml files;
- trying to install again and it does not work (Cluster ID error);

### Additional context

(With @adwk67 )

Some measures applied:
- deleted CRD's;
- uninstall/installed the operators;
The problem remains.

Related:
- https://amalgjose.com/2021/05/28/kafka-error-cluster-id-doesnt-match-stored-clusterid-in-meta-properties/

### Environment

Client Version: v1.25.3
Kustomize Version: v4.5.7
Server Version: v1.25.6

### Would you like to work on fixing this bug?

None

**Comment by adwk67** [comment]
Reproducable in a local kind cluster:

```
kind delete clusters --all
kind create cluster
stackablectl op in zookeeper=23.4.0 secret=23.4.0 commons=23.4.0 kafka=23.4.0

# 23.4.0 versions
kubectl apply -f - <<EOF
---
apiVersion: zookeeper.stackable.tech/v1alpha1
kind: ZookeeperCluster
metadata:
  name: simple-zk
spec:
  image:
    productVersion: 3.8.0
    stackableVersion: 23.4.0
  servers:
    roleGroups:
      primary:
        replicas: 1
        config:
          myidOffset: 10
---
apiVersion: zookeeper.stackable.tech/v1alpha1
kind: ZookeeperZnode
metadata:
  name: simple-zk-znode
spec:
  clusterRef:
    name: simple-zk
---
apiVersion: zookeeper.stackable.tech/v1alpha1
kind: ZookeeperZnode
metadata:
  name: simple-kafka-znode
spec:
  clusterRef:
    name: simple-zk
---
apiVersion: kafka.stackable.tech/v1alpha1
kind: KafkaCluster
metadata:
  name: simple-kafka
spec:
  image:
    productVersion: 3.3.1
    stackableVersion: 23.4.0
  clusterConfig:
    zookeeperConfigMapName: simple-kafka-znode
  brokers:
    roleGroups:
      default:
        replicas: 1
EOF

# wait until all pods are ready...

kubectl delete -f - <<EOF
---
apiVersion: zookeeper.stackable.tech/v1alpha1
kind: ZookeeperZnode
metadata:
  name: simple-kafka-znode
---
apiVersion: kafka.stackable.tech/v1alpha1
kind: KafkaCluster
metadata:
  name: simple-kafka
EOF

# wait until all pods are terminated...

stackablectl op un kafka
# update kafka CRD
kubectl replace -f https://raw.githubusercontent.com/stackabletech/kafka-operator/23.4.1/deploy/helm/kafka-operator/crds/crds.yaml

stackablectl op in kafka=23.4.1

# 23.4.1 version
kubectl apply -f - <<EOF
---
apiVersion: zookeeper.stackable.tech/v1alpha1
kind: ZookeeperZnode
metadata:
  name: simple-kafka-znode
spec:
  clusterRef:
    name: simple-zk
---
apiVersion: kafka.stackable.tech/v1alpha1
kind: KafkaCluster
metadata:
  name: simple-kafka
spec:
  image:
    productVersion: 3.3.1
    stackableVersion: 23.4.1
  clusterConfig:
    zookeeperConfigMapName: simple-kafka-znode
  brokers:
    roleGroups:
      default:
        replicas: 1
EOF

# end of reproduceable example
# kafka.common.InconsistentClusterIdException: The Cluster ID LrWO5WmGSLKWuKoIyJhvew doesn't match stored clusterId Some(KuPjNmJjQXqWyfA20Ovj2A) in meta.properties.



kubectl delete -f - <<EOF
---
apiVersion: zookeeper.stackable.tech/v1alpha1
kind: ZookeeperZnode
metadata:
  name: simple-kafka-znode
---
apiVersion: kafka.stackable.tech/v1alpha1
kind: KafkaCluster
metadata:
  name: simple-kafka
---
apiVersion: zookeeper.stackable.tech/v1alpha1
kind: ZookeeperCluster
metadata:
  name: simple-zk
---
apiVersion: zookeeper.stackable.tech/v1alpha1
kind: ZookeeperZnode
metadata:
  name: simple-zk-znode
EOF

# now delete the pvcs too:
# data-simple-zk-server-primary-0
# log-dirs-simple-kafka-broker-default-0

kubectl delete pvc data-simple-zk-server-primary-0
kubectl delete pvc log-dirs-simple-kafka-broker-default-0


kubectl apply -f - <<EOF
---
apiVersion: zookeeper.stackable.tech/v1alpha1
kind: ZookeeperCluster
metadata:
  name: simple-zk
spec:
  image:
    productVersion: 3.8.0
    stackableVersion: 23.4.0
  servers:
    roleGroups:
      primary:
        replicas: 1
        config:
          myidOffset: 10
---
apiVersion: zookeeper.stackable.tech/v1alpha1
kind: ZookeeperZnode
metadata:
  name: simple-zk-znode
spec:
  clusterRef:
    name: simple-zk
---
apiVersion: zookeeper.stackable.tech/v1alpha1
kind: ZookeeperZnode
metadata:
  name: simple-kafka-znode
spec:
  clusterRef:
    name: simple-zk
---
apiVersion: kafka.stackable.tech/v1alpha1
kind: KafkaCluster
metadata:
  name: simple-kafka
spec:
  image:
    productVersion: 3.3.1
    stackableVersion: 23.4.1
  clusterConfig:
    zookeeperConfigMapName: simple-kafka-znode
  brokers:
    roleGroups:
      default:
        replicas: 1
EOF
```

**Comment by adwk67** [comment]
The fix above (i.e. everything after `# end of reproduceable example`) can be simplified to just deleting the kafka cluster and znode, deleting the logs pvc and re-deploying the kafka cluster and znode:

```
kubectl delete -f - <<EOF
---
apiVersion: zookeeper.stackable.tech/v1alpha1
kind: ZookeeperZnode
metadata:
  name: simple-kafka-znode
---
apiVersion: kafka.stackable.tech/v1alpha1
kind: KafkaCluster
metadata:
  name: simple-kafka
EOF

# now delete the pvc too: log-dirs-simple-kafka-broker-default-0
kubectl delete pvc log-dirs-simple-kafka-broker-default-0


kubectl apply -f - <<EOF
---
apiVersion: zookeeper.stackable.tech/v1alpha1
kind: ZookeeperZnode
metadata:
  name: simple-kafka-znode
spec:
  clusterRef:
    name: simple-zk
---
apiVersion: kafka.stackable.tech/v1alpha1
kind: KafkaCluster
metadata:
  name: simple-kafka
spec:
  image:
    productVersion: 3.3.1
    stackableVersion: 23.4.1
  clusterConfig:
    zookeeperConfigMapName: simple-kafka-znode
  brokers:
    roleGroups:
      default:
        replicas: 1
EOF
```
