### ISSUE TITLE
Storage Config example in docs is wrong

### ISSUE THREAD

**Issue by soenkeliebau** [stackabletech/kafka-operator#667]
The [example](https://docs.stackable.tech/home/nightly/kafka/usage-guide/storage-resources#_storage_for_data_volumes) in the docs says:

```
brokers:
  roleGroups:
    default:
      config:
        resources:
          storage:
            data:
              capacity: 2Gi
```

Which fails to apply because `data` should be `logDirs`. The example further down the page is correct.
